// tools/check_globals.js - Detect duplicate global declarations across JS files
const fs = require('fs');
const path = require('path');

const jsDir = path.join(__dirname, '..', 'js');
const files = fs.readdirSync(jsDir).filter(f => f.endsWith('.js')).sort();
const mapMode = process.argv.includes('--map');

const declarations = new Map();
const re = /^\s{0,2}(?:let|var|const)\s+/;

for (const file of files) {
  const lines = fs.readFileSync(path.join(jsDir, file), 'utf8').split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!re.test(line)) continue;
    const stripped = line.replace(/^\s*(let|var|const)\s+/, '');
    const parts = stripped.split(',');
    for (const part of parts) {
      const vm = part.trim().match(/^([a-zA-Z_$][\w$]*)/);
      if (!vm) continue;
      const name = vm[1];
      if (!declarations.has(name)) declarations.set(name, []);
      declarations.get(name).push({ file, line: i + 1 });
    }
  }
}

if (mapMode) {
  const byFile = new Map();
  for (const [name, locs] of declarations) {
    for (const loc of locs) {
      if (!byFile.has(loc.file)) byFile.set(loc.file, []);
      byFile.get(loc.file).push(name);
    }
  }
  console.log('# VARIABLE_MAP_AUTO.md');
  console.log('# Auto-generated by tools/check_globals.js --map');
  console.log('');
  for (const [file, vars] of [...byFile.entries()].sort()) {
    console.log('## ' + file);
    console.log(vars.sort().join(', '));
    console.log('');
  }
  process.exit(0);
}

console.log('=== Global Declaration Check ===');
console.log('Files: ' + files.join(', '));
console.log('Total unique globals: ' + declarations.size);
console.log('');

let errors = 0;
for (const [name, locs] of declarations) {
  if (locs.length > 1) {
    errors++;
    console.log('[DUPLICATE] ' + name + ':');
    for (const loc of locs) console.log('  ' + loc.file + ' L' + loc.line);
  }
}

if (errors === 0) {
  console.log('[OK] No duplicate global declarations.');
} else {
  console.log('\n[FAIL] ' + errors + ' duplicate(s) found.');
}
process.exit(errors > 0 ? 1 : 0);